"""Constantes do ConcurseiroOS."""

# Gamificação
LEVEL_XP = 500
XP_PER_HOUR = 100
XP_PER_QUESTION = 10
XP_PER_CORRECT = 5
XP_PER_FLASHCARD = 5
XP_PER_TOPIC = 25
XP_PER_SIMULADO = 50
XP_STREAK_WEEKLY_BONUS = 200

# SM-2 Algorithm
SM2_INITIAL_EF = 2.5
SM2_MIN_EF = 1.3
SM2_FIRST_INTERVAL = 1
SM2_SECOND_INTERVAL = 6

# Treinador
WEIGHT_ACCURACY = 0.4
WEIGHT_PROGRESS = 0.3
WEIGHT_CONSISTENCY = 0.3
THRESHOLD_EXCELLENT = 80
THRESHOLD_GOOD = 60
THRESHOLD_REGULAR = 40
THRESHOLD_BEGINNER = 20

# Prova
DEFAULT_EXAM_DURATION_MIN = 180
DEFAULT_EXAM_QUESTIONS = 120
DEFAULT_TIME_PER_QUESTION_SEC = 90

# Metas
DEFAULT_META_HORAS = 3.0
DEFAULT_META_QUESTOES = 30
DEFAULT_META_FLASHCARDS = 10
DEFAULT_META_PAGINAS = 20

# Backup
MAX_BACKUPS = 7
BACKUP_INTERVAL_HOURS = 24

# Speed Review
SPEED_REVIEW_LIMIT = 20

# Paginacao
DEFAULT_PAGE_LIMIT = 50

# FSRS Algorithm
FSRS_DEFAULT_RETENTION = 0.9
FSRS_MIN_STABILITY = 0.01
FSRS_MAX_DIFFICULTY = 10.0
FSRS_MIN_DIFFICULTY = 1.0
