"""
Script para popular o banco com questões de exemplo para Batalhas.
Executar: python3 seed_questoes.py

Adiciona 50 questões variadas de Direito Constitucional, Administrativo e Português.
"""
import os
import sqlite3
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

DB_PATH = os.environ.get("DB_PATH", "./progress.db")

QUESTOES = [
    # Direito Constitucional - Fácil
    {
        "materia": "Direito Constitucional",
        "topico": "Princípios Fundamentais",
        "enunciado": "A República Federativa do Brasil tem como fundamento:",
        "alternativa_a": "A soberania, a cidadania e a dignidade da pessoa humana",
        "alternativa_b": "A independência nacional e a autodeterminação dos povos",
        "alternativa_c": "A defesa da paz e a solução pacífica dos conflitos",
        "alternativa_d": "A cooperação entre os povos para o progresso da humanidade",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Princípios Fundamentais",
        "enunciado": "São poderes da União, independentes e harmônicos entre si:",
        "alternativa_a": "O Legislativo, o Executivo e o Judiciário",
        "alternativa_b": "O Federal, o Estadual e o Municipal",
        "alternativa_c": "O Militar, o Civil e o Político",
        "alternativa_d": "O Legislativo, o Executivo e o Ministério Público",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FCC",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Direitos Fundamentais",
        "enunciado": "Todos são iguais perante a lei, sem distinção de qualquer natureza. Este princípio está previsto no:",
        "alternativa_a": "Art. 1° da CF",
        "alternativa_b": "Art. 5° da CF",
        "alternativa_c": "Art. 37 da CF",
        "alternativa_d": "Art. 144 da CF",
        "resposta_correta": "b",
        "dificuldade": "Fácil",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Direitos Fundamentais",
        "enunciado": "É livre a manifestação do pensamento, sendo vedado:",
        "alternativa_a": "O anonimato",
        "alternativa_b": "A identificação do autor",
        "alternativa_c": "A divulgação em redes sociais",
        "alternativa_d": "O uso de pseudônimo literário",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FGV",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Direitos Fundamentais",
        "enunciado": "O habeas corpus será concedido sempre que alguém sofrer ou se achar ameaçado de sofrer violência ou coação em sua liberdade de locomoção, por ilegalidade ou abuso de poder. Este remédio constitucional está previsto no:",
        "alternativa_a": "Art. 5°, LXVIII da CF",
        "alternativa_b": "Art. 5°, LXIX da CF",
        "alternativa_c": "Art. 5°, LXX da CF",
        "alternativa_d": "Art. 5°, LXXI da CF",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "CESPE",
    },
    # Direito Constitucional - Médio
    {
        "materia": "Direito Constitucional",
        "topico": "Organização do Estado",
        "enunciado": "Compete privativamente à União legislar sobre:",
        "alternativa_a": "Direito civil, comercial, penal, processual e eleitoral",
        "alternativa_b": "Proteção ao meio ambiente e controle da poluição",
        "alternativa_c": "Produção e consumo",
        "alternativa_d": "Educação, cultura, ensino e desporto",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Organização do Estado",
        "enunciado": "Sobre a organização político-administrativa, é correto afirmar que:",
        "alternativa_a": "Os Territórios Federais integram a União",
        "alternativa_b": "Os Municípios são entes federativos autônomos desde 1891",
        "alternativa_c": "O Distrito Federal pode ser dividido em municípios",
        "alternativa_d": "Os Estados podem incorporar-se entre si sem aprovação do Congresso",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FCC",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Poder Legislativo",
        "enunciado": "A Câmara dos Deputados compõe-se de representantes do povo, eleitos pelo sistema:",
        "alternativa_a": "Proporcional, em cada Estado e no DF",
        "alternativa_b": "Majoritário simples",
        "alternativa_c": "Majoritário absoluto",
        "alternativa_d": "Misto (proporcional e majoritário)",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FGV",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Poder Executivo",
        "enunciado": "O Presidente da República pode delegar as seguintes atribuições aos Ministros de Estado, EXCETO:",
        "alternativa_a": "Declarar guerra e celebrar a paz",
        "alternativa_b": "Prover os cargos públicos federais na forma da lei",
        "alternativa_c": "Conceder indulto e comutar penas",
        "alternativa_d": "Expedir decretos regulamentares",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Poder Judiciário",
        "enunciado": "Compete ao STF julgar originariamente:",
        "alternativa_a": "A ação direta de inconstitucionalidade de lei federal ou estadual",
        "alternativa_b": "Os conflitos de competência entre juízes federais",
        "alternativa_c": "Os mandados de segurança contra atos de Ministros de Estado",
        "alternativa_d": "As revisões criminais de suas decisões",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FCC",
    },
    # Direito Constitucional - Difícil
    {
        "materia": "Direito Constitucional",
        "topico": "Controle de Constitucionalidade",
        "enunciado": "Sobre o controle de constitucionalidade, é INCORRETO afirmar:",
        "alternativa_a": "A ADPF pode ser ajuizada por qualquer cidadão",
        "alternativa_b": "A ADI tem efeitos erga omnes e vinculante",
        "alternativa_c": "A ADC exige comprovação de controvérsia judicial relevante",
        "alternativa_d": "O controle difuso pode ser exercido por qualquer juiz",
        "resposta_correta": "a",
        "dificuldade": "Difícil",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Processo Legislativo",
        "enunciado": "Em relação às medidas provisórias, assinale a alternativa CORRETA:",
        "alternativa_a": "O prazo de 60 dias é contado a partir da publicação da MP",
        "alternativa_b": "A MP pode versar sobre matéria de lei complementar",
        "alternativa_c": "A reedição de MP revogada pelo Congresso é permitida na mesma sessão",
        "alternativa_d": "MPs não convertem em lei sem apreciação em 45 dias",
        "resposta_correta": "a",
        "dificuldade": "Difícil",
        "banca": "FGV",
    },
    # Direito Administrativo - Fácil
    {
        "materia": "Direito Administrativo",
        "topico": "Princípios da Administração",
        "enunciado": "São princípios expressos da Administração Pública, previstos no art. 37 da CF:",
        "alternativa_a": "Legalidade, impessoalidade, moralidade, publicidade e eficiência",
        "alternativa_b": "Legalidade, razoabilidade, proporcionalidade, motivação e eficiência",
        "alternativa_c": "Supremacia do interesse público, indisponibilidade, autotutela e motivação",
        "alternativa_d": "Legalidade, legitimidade, economicidade e eficiência",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Princípios da Administração",
        "enunciado": "O princípio da legalidade, na Administração Pública, significa que:",
        "alternativa_a": "O administrador só pode fazer o que a lei autoriza",
        "alternativa_b": "O administrador pode fazer tudo que a lei não proíbe",
        "alternativa_c": "O administrador deve seguir apenas as leis constitucionais",
        "alternativa_d": "O administrador pode agir livremente dentro do interesse público",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FCC",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Atos Administrativos",
        "enunciado": "São atributos dos atos administrativos:",
        "alternativa_a": "Presunção de legitimidade, imperatividade, autoexecutoriedade e tipicidade",
        "alternativa_b": "Legalidade, moralidade, eficiência e publicidade",
        "alternativa_c": "Competência, forma, finalidade, motivo e objeto",
        "alternativa_d": "Vinculação, discricionariedade, autotutela e controle",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FGV",
    },
    # Direito Administrativo - Médio
    {
        "materia": "Direito Administrativo",
        "topico": "Licitações",
        "enunciado": "Nos termos da Lei 14.133/2021, a modalidade licitatória para contratações de até R$ 1.430.000,00 de obras e serviços de engenharia é:",
        "alternativa_a": "Concorrência",
        "alternativa_b": "Tomada de preços",
        "alternativa_c": "Convite",
        "alternativa_d": "Pregão",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Servidores Públicos",
        "enunciado": "O servidor público estável só perderá o cargo mediante:",
        "alternativa_a": "Sentença judicial transitada em julgado ou PAD, ou avaliação periódica de desempenho",
        "alternativa_b": "Decisão do superior hierárquico fundamentada",
        "alternativa_c": "Processo administrativo sem ampla defesa",
        "alternativa_d": "Redução de despesas por decreto presidencial",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FCC",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Responsabilidade Civil",
        "enunciado": "A responsabilidade civil do Estado é:",
        "alternativa_a": "Objetiva, na modalidade risco administrativo",
        "alternativa_b": "Subjetiva, dependendo de dolo ou culpa",
        "alternativa_c": "Objetiva, na modalidade risco integral",
        "alternativa_d": "Subjetiva para atos omissivos e objetiva para comissivos",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Poderes Administrativos",
        "enunciado": "O poder regulamentar permite ao chefe do Executivo:",
        "alternativa_a": "Expedir decretos para a fiel execução das leis",
        "alternativa_b": "Criar direitos e obrigações não previstos em lei",
        "alternativa_c": "Inovar o ordenamento jurídico",
        "alternativa_d": "Substituir a lei por ato normativo próprio",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FGV",
    },
    # Direito Administrativo - Difícil
    {
        "materia": "Direito Administrativo",
        "topico": "Improbidade Administrativa",
        "enunciado": "Segundo a Lei 8.429/92, com alterações da Lei 14.230/21, o ato de improbidade que causa enriquecimento ilícito exige:",
        "alternativa_a": "Dolo específico do agente",
        "alternativa_b": "Culpa ou dolo",
        "alternativa_c": "Apenas conduta comissiva",
        "alternativa_d": "Nexo causal com dano ao erário",
        "resposta_correta": "a",
        "dificuldade": "Difícil",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Contratos Administrativos",
        "enunciado": "A teoria da imprevisão aplica-se aos contratos administrativos quando:",
        "alternativa_a": "Evento extraordinário e imprevisível onera excessivamente uma das partes",
        "alternativa_b": "O contratado descumpre cláusula contratual",
        "alternativa_c": "A administração altera unilateralmente o objeto",
        "alternativa_d": "Há atraso no pagamento por mais de 90 dias",
        "resposta_correta": "a",
        "dificuldade": "Difícil",
        "banca": "FCC",
    },
    # Língua Portuguesa - Fácil
    {
        "materia": "Língua Portuguesa",
        "topico": "Ortografia",
        "enunciado": "Assinale a alternativa em que todas as palavras estão grafadas corretamente:",
        "alternativa_a": "Privilégio, beneficência, empecilho",
        "alternativa_b": "Previlégio, beneficiência, empecilho",
        "alternativa_c": "Privilégio, beneficência, impecilho",
        "alternativa_d": "Previlégio, beneficência, impecilho",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "CESPE",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Acentuação",
        "enunciado": "São todas palavras proparoxítonas:",
        "alternativa_a": "Lâmpada, médico, árvore",
        "alternativa_b": "Café, sofá, jiló",
        "alternativa_c": "Parede, caderno, janela",
        "alternativa_d": "Urubu, caju, bambu",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FCC",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Classes de Palavras",
        "enunciado": "Na frase 'O rápido atleta venceu a corrida', a palavra 'rápido' exerce função de:",
        "alternativa_a": "Adjunto adnominal",
        "alternativa_b": "Predicativo do sujeito",
        "alternativa_c": "Complemento nominal",
        "alternativa_d": "Aposto",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FGV",
    },
    # Língua Portuguesa - Médio
    {
        "materia": "Língua Portuguesa",
        "topico": "Concordância Verbal",
        "enunciado": "Quanto à concordância verbal, está CORRETO:",
        "alternativa_a": "Fazem dez anos que não viajo",
        "alternativa_b": "Faz dez anos que não viajo",
        "alternativa_c": "Fazem dez anos que não viajamos",
        "alternativa_d": "Faz dez anos que não viajam",
        "resposta_correta": "b",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Regência Verbal",
        "enunciado": "Assinale a frase com regência verbal CORRETA:",
        "alternativa_a": "Assisti o filme ontem",
        "alternativa_b": "Assisti ao filme ontem",
        "alternativa_c": "Assisti no filme ontem",
        "alternativa_d": "Assisti pelo filme ontem",
        "resposta_correta": "b",
        "dificuldade": "Médio",
        "banca": "FCC",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Crase",
        "enunciado": "O uso da crase está CORRETO em:",
        "alternativa_a": "Refiro-me à matéria publicada ontem",
        "alternativa_b": "Refiro-me à você",
        "alternativa_c": "Fui à Paris no verão",
        "alternativa_d": "Ele chegou à casa cedo",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Interpretação de Texto",
        "enunciado": "Em um texto argumentativo, a tese corresponde à:",
        "alternativa_a": "Ideia central defendida pelo autor",
        "alternativa_b": "Introdução do texto",
        "alternativa_c": "Exemplificação dos argumentos",
        "alternativa_d": "Conclusão do raciocínio",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FGV",
    },
    # Língua Portuguesa - Difícil
    {
        "materia": "Língua Portuguesa",
        "topico": "Sintaxe",
        "enunciado": "Na oração 'É necessário que todos participem', a oração subordinada classifica-se como:",
        "alternativa_a": "Subordinada substantiva subjetiva",
        "alternativa_b": "Subordinada substantiva objetiva direta",
        "alternativa_c": "Subordinada adjetiva restritiva",
        "alternativa_d": "Subordinada adverbial causal",
        "resposta_correta": "a",
        "dificuldade": "Difícil",
        "banca": "CESPE",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Pontuação",
        "enunciado": "O emprego da vírgula está CORRETO em:",
        "alternativa_a": "Os alunos, que foram aprovados, receberão o diploma.",
        "alternativa_b": "Os alunos que, foram aprovados receberão o diploma.",
        "alternativa_c": "Os alunos que foram aprovados, receberão o diploma.",
        "alternativa_d": "Os, alunos que foram aprovados receberão o diploma.",
        "resposta_correta": "a",
        "dificuldade": "Difícil",
        "banca": "FCC",
    },
    # Mais questões variadas
    {
        "materia": "Direito Constitucional",
        "topico": "Direitos Sociais",
        "enunciado": "São direitos dos trabalhadores, previstos no art. 7° da CF, EXCETO:",
        "alternativa_a": "Participação nos lucros garantida em valor fixo por lei",
        "alternativa_b": "Salário mínimo fixado em lei",
        "alternativa_c": "Décimo terceiro salário",
        "alternativa_d": "Repouso semanal remunerado",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Nacionalidade",
        "enunciado": "São brasileiros natos:",
        "alternativa_a": "Os nascidos no Brasil, ainda que de pais estrangeiros não a serviço de seu país",
        "alternativa_b": "Todos os nascidos no exterior de pai ou mãe brasileiros",
        "alternativa_c": "Os estrangeiros naturalizados há mais de 15 anos",
        "alternativa_d": "Os nascidos em navios de guerra estrangeiros em águas brasileiras",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FGV",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Organização Administrativa",
        "enunciado": "As autarquias são:",
        "alternativa_a": "Pessoas jurídicas de direito público, criadas por lei específica",
        "alternativa_b": "Pessoas jurídicas de direito privado, criadas por decreto",
        "alternativa_c": "Órgãos públicos sem personalidade jurídica",
        "alternativa_d": "Empresas estatais de economia mista",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Organização Administrativa",
        "enunciado": "A descentralização administrativa ocorre quando:",
        "alternativa_a": "O Estado cria entidades com personalidade jurídica própria",
        "alternativa_b": "Um órgão distribui competências internamente",
        "alternativa_c": "O chefe delega atribuições a subordinados",
        "alternativa_d": "Há criação de novos departamentos no ministério",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FCC",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Coesão e Coerência",
        "enunciado": "O conectivo 'porquanto' expressa ideia de:",
        "alternativa_a": "Causa",
        "alternativa_b": "Consequência",
        "alternativa_c": "Concessão",
        "alternativa_d": "Condição",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Semântica",
        "enunciado": "São palavras parônimas:",
        "alternativa_a": "Comprimento e cumprimento",
        "alternativa_b": "Casa e lar",
        "alternativa_c": "Bonito e feio",
        "alternativa_d": "Manga (fruta) e manga (camisa)",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FGV",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Remédios Constitucionais",
        "enunciado": "O mandado de segurança coletivo pode ser impetrado por:",
        "alternativa_a": "Partido político com representação no Congresso Nacional",
        "alternativa_b": "Qualquer cidadão brasileiro",
        "alternativa_c": "O Ministério Público exclusivamente",
        "alternativa_d": "Empresas privadas de qualquer porte",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Processo Administrativo",
        "enunciado": "O prazo para a Administração anular seus próprios atos, quando eivados de vícios, é de:",
        "alternativa_a": "5 anos, salvo comprovada má-fé",
        "alternativa_b": "10 anos em qualquer caso",
        "alternativa_c": "2 anos a partir da ciência do vício",
        "alternativa_d": "Não há prazo decadencial",
        "resposta_correta": "a",
        "dificuldade": "Difícil",
        "banca": "FCC",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Vozes Verbais",
        "enunciado": "A transposição para a voz passiva de 'O governo aprovou a medida' é:",
        "alternativa_a": "A medida foi aprovada pelo governo",
        "alternativa_b": "A medida aprovou-se pelo governo",
        "alternativa_c": "Aprovou-se a medida o governo",
        "alternativa_d": "O governo foi aprovado pela medida",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FGV",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Administração Pública",
        "enunciado": "A investidura em cargo ou emprego público depende de:",
        "alternativa_a": "Aprovação prévia em concurso público de provas ou de provas e títulos",
        "alternativa_b": "Indicação do superior hierárquico",
        "alternativa_c": "Eleição popular para todos os cargos",
        "alternativa_d": "Apenas análise curricular",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Administração Pública",
        "enunciado": "O prazo de validade do concurso público é de até:",
        "alternativa_a": "Dois anos, prorrogável uma vez por igual período",
        "alternativa_b": "Três anos, improrrogável",
        "alternativa_c": "Um ano, prorrogável duas vezes",
        "alternativa_d": "Quatro anos, sem prorrogação",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FCC",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Bens Públicos",
        "enunciado": "Os bens públicos de uso comum do povo são:",
        "alternativa_a": "Inalienáveis enquanto conservarem a qualificação",
        "alternativa_b": "Alienáveis a qualquer tempo",
        "alternativa_c": "Passíveis de usucapião após 20 anos",
        "alternativa_d": "De uso exclusivo da administração",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Figuras de Linguagem",
        "enunciado": "Na frase 'Aquele homem é um touro', temos uma figura de linguagem chamada:",
        "alternativa_a": "Metáfora",
        "alternativa_b": "Metonímia",
        "alternativa_c": "Hipérbole",
        "alternativa_d": "Eufemismo",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FGV",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Tipos Textuais",
        "enunciado": "Um texto que apresenta fatos em sequência temporal é classificado como:",
        "alternativa_a": "Narrativo",
        "alternativa_b": "Dissertativo",
        "alternativa_c": "Descritivo",
        "alternativa_d": "Injuntivo",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Direitos Políticos",
        "enunciado": "O alistamento eleitoral e o voto são obrigatórios para:",
        "alternativa_a": "Maiores de 18 e menores de 70 anos",
        "alternativa_b": "Todos os brasileiros maiores de 16 anos",
        "alternativa_c": "Maiores de 18 anos sem exceção",
        "alternativa_d": "Maiores de 21 anos",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FCC",
    },
    {
        "materia": "Direito Administrativo",
        "topico": "Serviços Públicos",
        "enunciado": "O princípio da continuidade dos serviços públicos impede:",
        "alternativa_a": "A interrupção do serviço em situação de emergência",
        "alternativa_b": "A suspensão por inadimplemento do usuário, após aviso prévio",
        "alternativa_c": "A paralisação total sem justificativa técnica",
        "alternativa_d": "A delegação a particulares via concessão",
        "resposta_correta": "c",
        "dificuldade": "Médio",
        "banca": "CESPE",
    },
    {
        "materia": "Direito Constitucional",
        "topico": "Ordem Econômica",
        "enunciado": "A ordem econômica brasileira é fundada:",
        "alternativa_a": "Na valorização do trabalho humano e na livre iniciativa",
        "alternativa_b": "Exclusivamente na livre iniciativa",
        "alternativa_c": "No planejamento estatal obrigatório",
        "alternativa_d": "Na estatização dos meios de produção",
        "resposta_correta": "a",
        "dificuldade": "Fácil",
        "banca": "FGV",
    },
    {
        "materia": "Língua Portuguesa",
        "topico": "Pronomes",
        "enunciado": "O pronome 'lhe' substitui um complemento iniciado pela preposição:",
        "alternativa_a": "A (a ele/a ela)",
        "alternativa_b": "De (dele/dela)",
        "alternativa_c": "Com (com ele/ela)",
        "alternativa_d": "Para (para ele/ela)",
        "resposta_correta": "a",
        "dificuldade": "Médio",
        "banca": "FCC",
    },
]


def main():
    conn = sqlite3.connect(DB_PATH)
    now = datetime.now().isoformat()
    inserted = 0

    for q in QUESTOES:
        # Verificar se já existe (evitar duplicatas pelo enunciado)
        existing = conn.execute(
            "SELECT id FROM questoes WHERE enunciado = ? AND user_id = 1",
            (q["enunciado"],)
        ).fetchone()
        if existing:
            continue

        conn.execute("""
            INSERT INTO questoes (materia, topico, enunciado, alternativa_a, alternativa_b,
                                  alternativa_c, alternativa_d, alternativa_e, resposta_correta,
                                  dificuldade, banca, user_id, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)
        """, (
            q["materia"], q.get("topico", ""), q["enunciado"],
            q.get("alternativa_a", ""), q.get("alternativa_b", ""),
            q.get("alternativa_c", ""), q.get("alternativa_d", ""),
            q.get("alternativa_e", ""), q["resposta_correta"],
            q.get("dificuldade", "Médio"), q.get("banca", ""),
            now
        ))
        inserted += 1

    conn.commit()

    # Estatísticas finais
    total = conn.execute("SELECT COUNT(*) FROM questoes WHERE user_id = 1").fetchone()[0]
    por_materia = conn.execute("""
        SELECT materia, COUNT(*) as cnt FROM questoes WHERE user_id = 1
        GROUP BY materia ORDER BY cnt DESC
    """).fetchall()
    por_dif = conn.execute("""
        SELECT dificuldade, COUNT(*) as cnt FROM questoes WHERE user_id = 1
        GROUP BY dificuldade ORDER BY cnt DESC
    """).fetchall()
    com_resp = conn.execute("""
        SELECT COUNT(*) FROM questoes WHERE user_id = 1 AND resposta_correta != '' AND resposta_correta IS NOT NULL
    """).fetchone()[0]

    conn.close()

    print(f"✅ {inserted} questões inseridas (duplicatas ignoradas)")
    print(f"\n📊 Total de questões: {total}")
    print(f"   Com gabarito: {com_resp} ({100*com_resp//total}%)")
    print("\n📚 Por matéria:")
    for m in por_materia:
        print(f"   {m[0]}: {m[1]}")
    print("\n🎯 Por dificuldade:")
    for d in por_dif:
        print(f"   {d[0] or '(vazio)'}: {d[1]}")
    print(f"\n🎮 Batalhas: prontas para até {com_resp//3} rodadas sem repetição")


if __name__ == "__main__":
    main()
